baseURL = "/"
languageCode = "en-us"
title = "Claire Boals"
theme = "archie"
ignoreErrors = ["error-remote-getjson"]

 copyright = "Â© Claire Boals"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "A place for me to ramble freely."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/claireboals"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/claireboals/"

[[params.social]]
name = "E-mail"
icon = "mail"
url = "mailto:claireboals@gmail.com"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true